### ISSUE TITLE
Player control buttons missing

### ISSUE THREAD

**Issue by citronalco** [acrylian/mediaelementjs_player#13]
Icons for play, stop,... buttons are not displayed.
Browser complains it cannot find mejs-controls.svg.

After some digging I found an Issue at mediaelements, the proposed workaround works:
https://github.com/mediaelement/mediaelement/issues/2874#issuecomment-1007940355

**Comment by acrylian** [comment]
Thanks, this plugin is actually sort of abandoned as you can almost play everything natively via the browser now. 

But if you I welcome a pull request with the fix.
